# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: use-vector
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  stage: dev

package:
 exclude:
   - node_modules/**

functions:
  home:
    handler: handler.home
    events:
      - http:
          path: /
          method: get
          cors: true
  vectorise:
    handler: handler.vectorise
    timeout: 10 # optional, in seconds, default is 6
    events:
      - http:
          path: vectorise
          method: post
          cors: true
  vectoriseInPath:
    handler: handler.vectoriseInPath
    timeout: 10 # optional, in seconds, default is 6
    events:
      - http:
          path: /{text}/vector
          method: get
          cors: true
  similarity:
    handler: handler.similarity
    timeout: 15 # optional, in seconds, default is 6
    events:
      - http:
          path: similarity
          method: post
          cors: true

plugins:
  - serverless-plugin-include-dependencies
# custom:
#   webpackIncludeModules:
#     forceInclude:
#       - @tensorflow/tfjs
#       - @tensorflow-models/universal-sentence-encoder
